### ISSUE TITLE
Appropriate license?

### ISSUE THREAD

**Issue by rrelyea** [bogle-tools/financial-variables#1]
What is the best license to choose for the data we'd like to collect and share? Right now, we've not picked a license type.

**Comment by rrelyea** [comment]
Suggestion from bogleheads/trallium: https://www.bogleheads.org/forum/viewtopic.php?p=6929198#p6929198

> For data license, I'd take a look at https://creativecommons.org/publicdomain/zero/1.0/ or https://opendatacommons.org/licenses/pddl/1-0/

**Comment by mikhael28** [comment]
If you are posting as open-source, I would recommend just MIT. If you are trying to monetize, then you will need to provide some sort of higher-level value add apart from the data, but organizing the data is a good way of getting some community traction and engagement around your project.

**Comment by rrelyea** [comment]
Chose "CC0 1.0 Universal license" after a review a MIT vs Apache vs CC0 by my crack legal team. :-)

**Comment by rrelyea** [comment]
> If you are posting as open-source, I would recommend just MIT. If you are trying to monetize, then you will need to provide some sort of higher-level value add apart from the data, but organizing the data is a good way of getting some community traction and engagement around your project.

Thanks for the advice.
